[package]
name = "sqlite-uid"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.21.3"
rand = "0.9.1"
sqlite-loadable = "0.0.5"
uuid = {version="1.16.0", features=["v4"]}

[lib]
crate-type = ["cdylib"]
